### PR TITLE
Python3 Support

### PR DESCRIPTION
**Pull request by espdev**
- Support for Python 3.x has been added
- Formatting, Untabify

However, I think `fmm.cpp` needs refactoring.

### CODE REVIEW

**Comment by jkfurtney** [comment]
Wow, thanks! I will review and merge this as soon as possible. 

I will look at refactoring fmm.cpp as I agree it is a mess. If you have any recommendations for that let me know. 

Out of curiosity what do you use scikit-fmm for?

Thanks again.

**Comment by espdev** [comment]
@jkfurtney 

Thank you for you attention!

#### fmm
I want to use Fast Marching method and this package for search shortest paths through 2D gray-scale map (an image). Also I think it will need to port this Matlab code: http://www.mathworks.com/matlabcentral/fileexchange/24531-accurate-fast-marching

If you don't mind :)

#### Refactoring
I think need to add macros in `fmm.cpp` for readability. See also this link:
http://python3porting.com/cextensions.html

**Comment by jkfurtney** [comment]
@espdev thanks again for this. I merged this and a bunch of other branches today. Everything works for me in 32bit and 64bit on Ubuntu and Windows and with Python 2.7 and 3.4.

A while ago I added a Python wrapper for the binary min-heap that skfmm uses. This is useful for experimenting with fast-marching algorithms. I am also interested in experimenting with the multi-stencil methods implemented in that reference. 

Also I experimented with some path finding some time ago. The code is here:
https://github.com/scikit-fmm/scikit-fmm/wiki/optimal_path
if you get anything nice working it would make for a nice example in the docs.

Let me know if you have any problems with the current master. Otherwise, I will do some clean up in fmm.cpp and push out a new version to PyPI some time next week.

**Comment by espdev** [comment]
@jkfurtney Thanks! The code from the current master works fine! I have installed skfmm via pip and checked it on Windows with Python 2.7 and 3.4.

Thanks for link to "optimal_path" code! I will try to make a few examples and try to experiment with it.

**Pull request merged**
