### PR TITLE
Fixing pip-installing at the same time as numpy

### PR DESCRIPTION
**Pull request by ManifoldFR**
Treat `egg_info` and some other commands differently when running setup_package

I'm not entirely sure this will work, I looked at what was done for SciPy's setup.py and [this issue](https://github.com/scikit-learn-contrib/py-earth/issues/60) for py-earth. It seems it's a case of the infamous pip [issue #25](https://github.com/pypa/pip/issues/25)

### CODE REVIEW

**Comment by ManifoldFR** [comment]
I am pretty sure my fix works: the Travis run is able to build the package and works up until the testing part (I think that's normal ?), and I've successfully tested pip-installing scikit-fmm with `numpy` simultaneously from a `requirements.txt` file on my local machine.

**Comment by jkfurtney** [comment]
Thanks for getting in touch and thanks your efforts on this. I will have a look at this and merge as soon as I can. The Travis and Appveyor builds are currently failing because I added tests for a known bug. I should flag those tests as known failures.

**Comment by ShadowTemplate** [comment]
Hi! Any update on this pull request?
Right now scikit-fmm and numpy can't still be simultaneously installed from a requirements.txt.
Does the solution proposed by ManifoldFR fix the issue?

**Comment by jkfurtney** [comment]
Hi, Thanks for the note and sorry I have neglected this PR. I will have some time Sunday or early next week to look into this.

**Comment by jkfurtney** [comment]
OK, I think I am on the same page now. When I try `pip install numpy scikit-fmm` I get the following. Is this what you get? I will try your patch now.

```bash
jkf@whippie:~$ virtualenv sktest
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/jkf/sktest/bin/python2
Also creating executable in /home/jkf/sktest/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
jkf@whippie:~$ source sktest/bin/activate
(sktest) jkf@whippie:~$
(sktest) jkf@whippie:~$ pip install numpy scikit-fmm
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/9f/85/163127d3fb0573deb9eca947cfc73aa3618eaaf8656501460574471d114a/numpy-1.16.0-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |████████████████████████████████| 17.0MB 1.6MB/s
Collecting scikit-fmm
  Downloading https://files.pythonhosted.org/packages/0b/fd/2bb33ca6114c2e8c76f19768eb68d0fcc10ec7aba854671d9c9448626da6/scikit-fmm-0.0.9.tar.gz (414kB)
    100% |████████████████████████████████| 419kB 11.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4Cc88u/scikit-fmm/setup.py", line 65, in <module>
        setup_package()
      File "/tmp/pip-install-4Cc88u/scikit-fmm/setup.py", line 42, in setup_package
        from numpy.distutils.core import setup
    ImportError: No module named numpy.distutils.core

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4Cc88u/scikit-fmm/```

**Comment by ManifoldFR** [comment]
Yup, that's pretty much what I was getting.

**Comment by jkfurtney** [comment]
Your fix also works for me. I merged this PR branch into master. 

@ManifoldFR let me know what name you want in the CONTRIBUTORS.txt file, for now I just added ManifoldFR.

Once I fix the TravisCI build and check a few other things I will push a new release to PyPI.

Thanks again.

**Comment by ManifoldFR** [comment]
ManifoldFR is fine, but I think I accidentally committed binary files (`.pyd`) in my PR, so you might have to remove them

**Comment by jkfurtney** [comment]
I will close this now. I just pushed out a release with this fix merged in.

**Pull request closed without merging**
