### PR TITLE
updating main documentation; adding periodic boundary condition test

### PR DESCRIPTION
**Pull request by wmoebius**

### CODE REVIEW

**Comment by jkfurtney** [comment]
Thanks for this. I will merge this into master soon and push out a release.

**Comment by wmoebius** [comment]
I realize my commit sounded like more than I actually did...

I did two things:

- updating the main documentation, but not for periodic yet, but the masking issue I had asked you in my first email. I'm ready to update documentation of distance and travel_time (only these two, right), if you hint me in the direction of where that goes.

- created a test/example file: that needs to be split up into the test and the 2d_example.py. Can you hint me in the direction of where the tests go? I'll then base the pbc example on your example in 2d_example.py, we just need to change phi because otherwise we create another zero contour...

Thanks!

**Comment by jkfurtney** [comment]
The docstrings for the functions are in: 

https://github.com/scikit-fmm/scikit-fmm/blob/periodic/skfmm/pfmm.py

The tests are in:

https://github.com/scikit-fmm/scikit-fmm/blob/periodic/skfmm/__init__.py 

in doctest format. Could you put the new tests at the bottom of the tests please? 

I think the new example will need to be added to the sphinx documentation files. I can take care of that.

Thanks again.

**Comment by wmoebius** [comment]
OK, I'll do the following things:

Modify the docstrings for the functions.

Add the tests at the bottom of the tests.

Modify the existing 2d_example. You can than use that as a basis to change the actual documentation files.

I'll make a new pull request when I'm ready.

Thanks, Wolfram

**Comment by wmoebius** [comment]
Three short questions:

- Does periodic really make sense for extension_velocities()? I can add the argument to the doc, but I don't see how to construct an example or a test.

- distance() gives a signed result. This is probably intentional? Would like to make that clearer in the doc (and it's confusing in my example). How's inward/outward defined?

- you write array-like as a description for arguments. Can I specify that as 'list, tuple, numpy array'?

**Comment by jkfurtney** [comment]
* Let's stick to `distance()` and `travel_time()` for now. I will experiment with `extension_velocities()`. My first instinct is that it should work.

* Yes, `distance()` is supposed to return a signed result. It would be great if you could clarify this in the documentation. The negative distance is on the negative side of the zero contour of phi, as in this example.

```python
 skfmm.distance((-1,1))
 array([-0.5,  0.5])
```

* Array-like is a term used by `numpy` to describe an object which can be converted into an array via `np.array()`. It includes more than list, tuples and arrays. Any object which defines a length and an element wise look up operation can be converted to a numpy array. I think this is an established term so let's keep it.

**Pull request merged**
