### PR TITLE
wheel for python 39

### PR DESCRIPTION
**Pull request by fbordignon**
Trying to add wheels for newer python versions

### CODE REVIEW

**Comment by jkfurtney** [comment]
Thanks for this, if everything passes with these builds I will merge the PR and get the wheel files uploaded to PyPI.

**Comment by jkfurtney** [comment]
Another option here is to migrate the builds to GitHub Actions, it looks like that is how other projects do it.

**Comment by fbordignon** [comment]
I am basically going by trial and error here. I don't know much about github actions as well, but will give it a try

**Comment by fbordignon** [comment]
Ok, it is working on python 39 but 3.10 removed support for bdist_wininst. I don't have much time to fix it, so I will leave it with python 3.9. If someone could be kind enough to update the setup flow it would be wonderful. Thanks

On a side note, python 36 reached EOL, so fmm could move to visual studio 2022 image entirely if cp 36 support is dropped.

**Comment by jkfurtney** [comment]
Thanks again, I will get the 3.9 wheel on PyPI.  I took out the 3.6 build and removed the bdist_wininst. I will look into 3.10 build.

**Comment by fbordignon** [comment]
Thanks, @jkfurtney I've tested on a machine that don't have access to ms build tools and the pip install worked. Well done!

**Pull request merged**
