### PR TITLE
Speed optimizations

### PR DESCRIPTION
**Pull request by okonrad**
* Using explicit multiplication a*a instead of slower pow(a,2)
* Terminating early when scanning neighborhood
* Only computing neighborhood offset that is needed instead of computing all offsets and just use one of them

### CODE REVIEW

**Comment by jkfurtney** [comment]
Thanks for these additional optimizations. The tests involving masked arrays and the periodic boundaries are failing. Did the tests pass on your machine? If so, what platform are you using?

**Comment by okonrad** [comment]
We use a different version because we directly use the code in a C++ environment, there is no Python in use for us. Some options, like periodic boundaries are not used by us. 

We obviously did not merge correctly back, sorry for that. We need to figure out how to run those tests, then we will get back to you.

**Comment by okonrad** [comment]
We optimized the code for our specific needs; will only change the pow(a,2) to a*a next time.

I could not get AppVeyor to build (and subsequently test) because it fails to find its own compiler.

**Comment by jkfurtney** [comment]
Thanks for the explanation, the AppVeyer build is failing for some other reason, due to the C++ auto I think. I have a separate issue #46 for that one, I will take care of it soon.

**Pull request closed without merging**
